/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PainelRouteImport } from './routes/_painel'
import { Route as PainelConfiguracoesRouteImport } from './routes/_painel.configuracoes'
import { Route as PainelDashboardRouteImport } from './routes/_painel.dashboard'
import { Route as PainelSuporteRouteImport } from './routes/_painel.suporte'
import { Route as PainelClientesIndexRouteImport } from './routes/_painel.clientes.index'
import { Route as PainelClientesCnpjRouteImport } from './routes/_painel.clientes.$cnpj'
import { Route as PainelClientesNovoRouteImport } from './routes/_painel.clientes.novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/_painel',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelConfiguracoesRoute = PainelConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => PainelRoute,
} as any)
const PainelDashboardRoute = PainelDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PainelRoute,
} as any)
const PainelSuporteRoute = PainelSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => PainelRoute,
} as any)
const PainelClientesIndexRoute = PainelClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => PainelRoute,
} as any)
const PainelClientesCnpjRoute = PainelClientesCnpjRouteImport.update({
  id: '/clientes/$cnpj',
  path: '/clientes/$cnpj',
  getParentRoute: () => PainelRoute,
} as any)
const PainelClientesNovoRoute = PainelClientesNovoRouteImport.update({
  id: '/clientes/novo',
  path: '/clientes/novo',
  getParentRoute: () => PainelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof PainelConfiguracoesRoute
  '/dashboard': typeof PainelDashboardRoute
  '/suporte': typeof PainelSuporteRoute
  '/clientes/$cnpj': typeof PainelClientesCnpjRoute
  '/clientes/novo': typeof PainelClientesNovoRoute
  '/clientes/': typeof PainelClientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof PainelConfiguracoesRoute
  '/dashboard': typeof PainelDashboardRoute
  '/suporte': typeof PainelSuporteRoute
  '/clientes/$cnpj': typeof PainelClientesCnpjRoute
  '/clientes/novo': typeof PainelClientesNovoRoute
  '/clientes': typeof PainelClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_painel': typeof PainelRouteWithChildren
  '/_painel/configuracoes': typeof PainelConfiguracoesRoute
  '/_painel/dashboard': typeof PainelDashboardRoute
  '/_painel/suporte': typeof PainelSuporteRoute
  '/_painel/clientes/$cnpj': typeof PainelClientesCnpjRoute
  '/_painel/clientes/novo': typeof PainelClientesNovoRoute
  '/_painel/clientes/': typeof PainelClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/dashboard'
    | '/suporte'
    | '/clientes/$cnpj'
    | '/clientes/novo'
    | '/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/dashboard'
    | '/suporte'
    | '/clientes/$cnpj'
    | '/clientes/novo'
    | '/clientes'
  id:
    | '__root__'
    | '/'
    | '/_painel'
    | '/_painel/configuracoes'
    | '/_painel/dashboard'
    | '/_painel/suporte'
    | '/_painel/clientes/$cnpj'
    | '/_painel/clientes/novo'
    | '/_painel/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PainelRoute: typeof PainelRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_painel': {
      id: '/_painel'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_painel/configuracoes': {
      id: '/_painel/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof PainelConfiguracoesRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/dashboard': {
      id: '/_painel/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PainelDashboardRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/suporte': {
      id: '/_painel/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof PainelSuporteRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/clientes/': {
      id: '/_painel/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof PainelClientesIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/clientes/$cnpj': {
      id: '/_painel/clientes/$cnpj'
      path: '/clientes/$cnpj'
      fullPath: '/clientes/$cnpj'
      preLoaderRoute: typeof PainelClientesCnpjRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/clientes/novo': {
      id: '/_painel/clientes/novo'
      path: '/clientes/novo'
      fullPath: '/clientes/novo'
      preLoaderRoute: typeof PainelClientesNovoRouteImport
      parentRoute: typeof PainelRoute
    }
  }
}

interface PainelRouteChildren {
  PainelConfiguracoesRoute: typeof PainelConfiguracoesRoute
  PainelDashboardRoute: typeof PainelDashboardRoute
  PainelSuporteRoute: typeof PainelSuporteRoute
  PainelClientesCnpjRoute: typeof PainelClientesCnpjRoute
  PainelClientesNovoRoute: typeof PainelClientesNovoRoute
  PainelClientesIndexRoute: typeof PainelClientesIndexRoute
}

const PainelRouteChildren: PainelRouteChildren = {
  PainelConfiguracoesRoute: PainelConfiguracoesRoute,
  PainelDashboardRoute: PainelDashboardRoute,
  PainelSuporteRoute: PainelSuporteRoute,
  PainelClientesCnpjRoute: PainelClientesCnpjRoute,
  PainelClientesNovoRoute: PainelClientesNovoRoute,
  PainelClientesIndexRoute: PainelClientesIndexRoute,
}

const PainelRouteWithChildren =
  PainelRoute._addFileChildren(PainelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PainelRoute: PainelRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
