/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PainelRouteImport } from './routes/_painel'
import { Route as PainelConfiguracoesRouteImport } from './routes/_painel.configuracoes'
import { Route as PainelDashboardRouteImport } from './routes/_painel.dashboard'
import { Route as PainelDestinatariosRouteImport } from './routes/_painel.destinatarios'
import { Route as PainelFiscalRouteImport } from './routes/_painel.fiscal'
import { Route as PainelRelatoriosRouteImport } from './routes/_painel.relatorios'
import { Route as PainelSuporteRouteImport } from './routes/_painel.suporte'
import { Route as PainelNfceIndexRouteImport } from './routes/_painel.nfce.index'
import { Route as PainelNfceIdRouteImport } from './routes/_painel.nfce.$id'
import { Route as PainelNfceEmitirRouteImport } from './routes/_painel.nfce.emitir'
import { Route as PainelNfeIndexRouteImport } from './routes/_painel.nfe.index'
import { Route as PainelNfeIdRouteImport } from './routes/_painel.nfe.$id'
import { Route as PainelNfeComprasRouteImport } from './routes/_painel.nfe.compras'
import { Route as PainelNfeEmitirRouteImport } from './routes/_painel.nfe.emitir'
import { Route as PainelNfeInutilizarRouteImport } from './routes/_painel.nfe.inutilizar'
import { Route as PainelNfseIndexRouteImport } from './routes/_painel.nfse.index'
import { Route as PainelNfseIdRouteImport } from './routes/_painel.nfse.$id'
import { Route as PainelNfseEmitirRouteImport } from './routes/_painel.nfse.emitir'
import { Route as PainelNfseRadarRouteImport } from './routes/_painel.nfse.radar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/_painel',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelConfiguracoesRoute = PainelConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => PainelRoute,
} as any)
const PainelDashboardRoute = PainelDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PainelRoute,
} as any)
const PainelDestinatariosRoute = PainelDestinatariosRouteImport.update({
  id: '/destinatarios',
  path: '/destinatarios',
  getParentRoute: () => PainelRoute,
} as any)
const PainelFiscalRoute = PainelFiscalRouteImport.update({
  id: '/fiscal',
  path: '/fiscal',
  getParentRoute: () => PainelRoute,
} as any)
const PainelRelatoriosRoute = PainelRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => PainelRoute,
} as any)
const PainelSuporteRoute = PainelSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => PainelRoute,
} as any)
const PainelNfceIndexRoute = PainelNfceIndexRouteImport.update({
  id: '/nfce/',
  path: '/nfce/',
  getParentRoute: () => PainelRoute,
} as any)
const PainelNfceIdRoute = PainelNfceIdRouteImport.update({
  id: '/nfce/$id',
  path: '/nfce/$id',
  getParentRoute: () => PainelRoute,
} as any)
const PainelNfceEmitirRoute = PainelNfceEmitirRouteImport.update({
  id: '/nfce/emitir',
  path: '/nfce/emitir',
  getParentRoute: () => PainelRoute,
} as any)
const PainelNfeIndexRoute = PainelNfeIndexRouteImport.update({
  id: '/nfe/',
  path: '/nfe/',
  getParentRoute: () => PainelRoute,
} as any)
const PainelNfeIdRoute = PainelNfeIdRouteImport.update({
  id: '/nfe/$id',
  path: '/nfe/$id',
  getParentRoute: () => PainelRoute,
} as any)
const PainelNfeComprasRoute = PainelNfeComprasRouteImport.update({
  id: '/nfe/compras',
  path: '/nfe/compras',
  getParentRoute: () => PainelRoute,
} as any)
const PainelNfeEmitirRoute = PainelNfeEmitirRouteImport.update({
  id: '/nfe/emitir',
  path: '/nfe/emitir',
  getParentRoute: () => PainelRoute,
} as any)
const PainelNfeInutilizarRoute = PainelNfeInutilizarRouteImport.update({
  id: '/nfe/inutilizar',
  path: '/nfe/inutilizar',
  getParentRoute: () => PainelRoute,
} as any)
const PainelNfseIndexRoute = PainelNfseIndexRouteImport.update({
  id: '/nfse/',
  path: '/nfse/',
  getParentRoute: () => PainelRoute,
} as any)
const PainelNfseIdRoute = PainelNfseIdRouteImport.update({
  id: '/nfse/$id',
  path: '/nfse/$id',
  getParentRoute: () => PainelRoute,
} as any)
const PainelNfseEmitirRoute = PainelNfseEmitirRouteImport.update({
  id: '/nfse/emitir',
  path: '/nfse/emitir',
  getParentRoute: () => PainelRoute,
} as any)
const PainelNfseRadarRoute = PainelNfseRadarRouteImport.update({
  id: '/nfse/radar',
  path: '/nfse/radar',
  getParentRoute: () => PainelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof PainelConfiguracoesRoute
  '/dashboard': typeof PainelDashboardRoute
  '/destinatarios': typeof PainelDestinatariosRoute
  '/fiscal': typeof PainelFiscalRoute
  '/relatorios': typeof PainelRelatoriosRoute
  '/suporte': typeof PainelSuporteRoute
  '/nfce/$id': typeof PainelNfceIdRoute
  '/nfce/emitir': typeof PainelNfceEmitirRoute
  '/nfe/$id': typeof PainelNfeIdRoute
  '/nfe/compras': typeof PainelNfeComprasRoute
  '/nfe/emitir': typeof PainelNfeEmitirRoute
  '/nfe/inutilizar': typeof PainelNfeInutilizarRoute
  '/nfse/$id': typeof PainelNfseIdRoute
  '/nfse/emitir': typeof PainelNfseEmitirRoute
  '/nfse/radar': typeof PainelNfseRadarRoute
  '/nfce/': typeof PainelNfceIndexRoute
  '/nfe/': typeof PainelNfeIndexRoute
  '/nfse/': typeof PainelNfseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof PainelConfiguracoesRoute
  '/dashboard': typeof PainelDashboardRoute
  '/destinatarios': typeof PainelDestinatariosRoute
  '/fiscal': typeof PainelFiscalRoute
  '/relatorios': typeof PainelRelatoriosRoute
  '/suporte': typeof PainelSuporteRoute
  '/nfce/$id': typeof PainelNfceIdRoute
  '/nfce/emitir': typeof PainelNfceEmitirRoute
  '/nfe/$id': typeof PainelNfeIdRoute
  '/nfe/compras': typeof PainelNfeComprasRoute
  '/nfe/emitir': typeof PainelNfeEmitirRoute
  '/nfe/inutilizar': typeof PainelNfeInutilizarRoute
  '/nfse/$id': typeof PainelNfseIdRoute
  '/nfse/emitir': typeof PainelNfseEmitirRoute
  '/nfse/radar': typeof PainelNfseRadarRoute
  '/nfce': typeof PainelNfceIndexRoute
  '/nfe': typeof PainelNfeIndexRoute
  '/nfse': typeof PainelNfseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_painel': typeof PainelRouteWithChildren
  '/_painel/configuracoes': typeof PainelConfiguracoesRoute
  '/_painel/dashboard': typeof PainelDashboardRoute
  '/_painel/destinatarios': typeof PainelDestinatariosRoute
  '/_painel/fiscal': typeof PainelFiscalRoute
  '/_painel/relatorios': typeof PainelRelatoriosRoute
  '/_painel/suporte': typeof PainelSuporteRoute
  '/_painel/nfce/$id': typeof PainelNfceIdRoute
  '/_painel/nfce/emitir': typeof PainelNfceEmitirRoute
  '/_painel/nfe/$id': typeof PainelNfeIdRoute
  '/_painel/nfe/compras': typeof PainelNfeComprasRoute
  '/_painel/nfe/emitir': typeof PainelNfeEmitirRoute
  '/_painel/nfe/inutilizar': typeof PainelNfeInutilizarRoute
  '/_painel/nfse/$id': typeof PainelNfseIdRoute
  '/_painel/nfse/emitir': typeof PainelNfseEmitirRoute
  '/_painel/nfse/radar': typeof PainelNfseRadarRoute
  '/_painel/nfce/': typeof PainelNfceIndexRoute
  '/_painel/nfe/': typeof PainelNfeIndexRoute
  '/_painel/nfse/': typeof PainelNfseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/dashboard'
    | '/destinatarios'
    | '/fiscal'
    | '/relatorios'
    | '/suporte'
    | '/nfce/$id'
    | '/nfce/emitir'
    | '/nfe/$id'
    | '/nfe/compras'
    | '/nfe/emitir'
    | '/nfe/inutilizar'
    | '/nfse/$id'
    | '/nfse/emitir'
    | '/nfse/radar'
    | '/nfce/'
    | '/nfe/'
    | '/nfse/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/dashboard'
    | '/destinatarios'
    | '/fiscal'
    | '/relatorios'
    | '/suporte'
    | '/nfce/$id'
    | '/nfce/emitir'
    | '/nfe/$id'
    | '/nfe/compras'
    | '/nfe/emitir'
    | '/nfe/inutilizar'
    | '/nfse/$id'
    | '/nfse/emitir'
    | '/nfse/radar'
    | '/nfce'
    | '/nfe'
    | '/nfse'
  id:
    | '__root__'
    | '/'
    | '/_painel'
    | '/_painel/configuracoes'
    | '/_painel/dashboard'
    | '/_painel/destinatarios'
    | '/_painel/fiscal'
    | '/_painel/relatorios'
    | '/_painel/suporte'
    | '/_painel/nfce/$id'
    | '/_painel/nfce/emitir'
    | '/_painel/nfe/$id'
    | '/_painel/nfe/compras'
    | '/_painel/nfe/emitir'
    | '/_painel/nfe/inutilizar'
    | '/_painel/nfse/$id'
    | '/_painel/nfse/emitir'
    | '/_painel/nfse/radar'
    | '/_painel/nfce/'
    | '/_painel/nfe/'
    | '/_painel/nfse/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PainelRoute: typeof PainelRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_painel': {
      id: '/_painel'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_painel/configuracoes': {
      id: '/_painel/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof PainelConfiguracoesRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/dashboard': {
      id: '/_painel/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PainelDashboardRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/destinatarios': {
      id: '/_painel/destinatarios'
      path: '/destinatarios'
      fullPath: '/destinatarios'
      preLoaderRoute: typeof PainelDestinatariosRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/fiscal': {
      id: '/_painel/fiscal'
      path: '/fiscal'
      fullPath: '/fiscal'
      preLoaderRoute: typeof PainelFiscalRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/relatorios': {
      id: '/_painel/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof PainelRelatoriosRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/suporte': {
      id: '/_painel/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof PainelSuporteRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/nfce/': {
      id: '/_painel/nfce/'
      path: '/nfce'
      fullPath: '/nfce/'
      preLoaderRoute: typeof PainelNfceIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/nfce/$id': {
      id: '/_painel/nfce/$id'
      path: '/nfce/$id'
      fullPath: '/nfce/$id'
      preLoaderRoute: typeof PainelNfceIdRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/nfce/emitir': {
      id: '/_painel/nfce/emitir'
      path: '/nfce/emitir'
      fullPath: '/nfce/emitir'
      preLoaderRoute: typeof PainelNfceEmitirRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/nfe/': {
      id: '/_painel/nfe/'
      path: '/nfe'
      fullPath: '/nfe/'
      preLoaderRoute: typeof PainelNfeIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/nfe/$id': {
      id: '/_painel/nfe/$id'
      path: '/nfe/$id'
      fullPath: '/nfe/$id'
      preLoaderRoute: typeof PainelNfeIdRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/nfe/compras': {
      id: '/_painel/nfe/compras'
      path: '/nfe/compras'
      fullPath: '/nfe/compras'
      preLoaderRoute: typeof PainelNfeComprasRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/nfe/emitir': {
      id: '/_painel/nfe/emitir'
      path: '/nfe/emitir'
      fullPath: '/nfe/emitir'
      preLoaderRoute: typeof PainelNfeEmitirRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/nfe/inutilizar': {
      id: '/_painel/nfe/inutilizar'
      path: '/nfe/inutilizar'
      fullPath: '/nfe/inutilizar'
      preLoaderRoute: typeof PainelNfeInutilizarRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/nfse/': {
      id: '/_painel/nfse/'
      path: '/nfse'
      fullPath: '/nfse/'
      preLoaderRoute: typeof PainelNfseIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/nfse/$id': {
      id: '/_painel/nfse/$id'
      path: '/nfse/$id'
      fullPath: '/nfse/$id'
      preLoaderRoute: typeof PainelNfseIdRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/nfse/emitir': {
      id: '/_painel/nfse/emitir'
      path: '/nfse/emitir'
      fullPath: '/nfse/emitir'
      preLoaderRoute: typeof PainelNfseEmitirRouteImport
      parentRoute: typeof PainelRoute
    }
    '/_painel/nfse/radar': {
      id: '/_painel/nfse/radar'
      path: '/nfse/radar'
      fullPath: '/nfse/radar'
      preLoaderRoute: typeof PainelNfseRadarRouteImport
      parentRoute: typeof PainelRoute
    }
  }
}

interface PainelRouteChildren {
  PainelConfiguracoesRoute: typeof PainelConfiguracoesRoute
  PainelDashboardRoute: typeof PainelDashboardRoute
  PainelDestinatariosRoute: typeof PainelDestinatariosRoute
  PainelFiscalRoute: typeof PainelFiscalRoute
  PainelRelatoriosRoute: typeof PainelRelatoriosRoute
  PainelSuporteRoute: typeof PainelSuporteRoute
  PainelNfceIdRoute: typeof PainelNfceIdRoute
  PainelNfceEmitirRoute: typeof PainelNfceEmitirRoute
  PainelNfeIdRoute: typeof PainelNfeIdRoute
  PainelNfeComprasRoute: typeof PainelNfeComprasRoute
  PainelNfeEmitirRoute: typeof PainelNfeEmitirRoute
  PainelNfeInutilizarRoute: typeof PainelNfeInutilizarRoute
  PainelNfseIdRoute: typeof PainelNfseIdRoute
  PainelNfseEmitirRoute: typeof PainelNfseEmitirRoute
  PainelNfseRadarRoute: typeof PainelNfseRadarRoute
  PainelNfceIndexRoute: typeof PainelNfceIndexRoute
  PainelNfeIndexRoute: typeof PainelNfeIndexRoute
  PainelNfseIndexRoute: typeof PainelNfseIndexRoute
}

const PainelRouteChildren: PainelRouteChildren = {
  PainelConfiguracoesRoute: PainelConfiguracoesRoute,
  PainelDashboardRoute: PainelDashboardRoute,
  PainelDestinatariosRoute: PainelDestinatariosRoute,
  PainelFiscalRoute: PainelFiscalRoute,
  PainelRelatoriosRoute: PainelRelatoriosRoute,
  PainelSuporteRoute: PainelSuporteRoute,
  PainelNfceIdRoute: PainelNfceIdRoute,
  PainelNfceEmitirRoute: PainelNfceEmitirRoute,
  PainelNfeIdRoute: PainelNfeIdRoute,
  PainelNfeComprasRoute: PainelNfeComprasRoute,
  PainelNfeEmitirRoute: PainelNfeEmitirRoute,
  PainelNfeInutilizarRoute: PainelNfeInutilizarRoute,
  PainelNfseIdRoute: PainelNfseIdRoute,
  PainelNfseEmitirRoute: PainelNfseEmitirRoute,
  PainelNfseRadarRoute: PainelNfseRadarRoute,
  PainelNfceIndexRoute: PainelNfceIndexRoute,
  PainelNfeIndexRoute: PainelNfeIndexRoute,
  PainelNfseIndexRoute: PainelNfseIndexRoute,
}

const PainelRouteWithChildren =
  PainelRoute._addFileChildren(PainelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PainelRoute: PainelRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
